<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z">
    <xacro:property name="damping_coef" value="0.7" />
    <xacro:property name="friction_coef" value="0.5" />
    <xacro:property name="tow_hitch_mass" value="0.5" />
    <xacro:property name="cargo_cart_link_mass" value="2" />
    <xacro:property name="dead_weight" value="5" />
    <xacro:property name="wheel_holder_mass" value="0.1" />
    <xacro:property name="wheel_mass" value="0.5" />
    <xacro:property name="wheel_radu" value="0.05" />
    <xacro:property name="wheel_with" value="0.02" />

    <link name="base_footprint"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
          <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>


    <link name="link1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.492 0.447 0.184"/>
          <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.492 0.447 0.184"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>


    <!--<link name="top_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.005" length="0.005"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.005" length="0.005"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.01" ixy="0" ixz="0"
                 iyy="0.01" iyz="0"
                 izz="0.01" />
      </inertial>
    </link>-->

    <link name="tow_hitch_link">
      <visual>
        <origin xyz="0 0 0.0125" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.05" length="0.025"/>
        </geometry>
        <material name="yellow"/>
      </visual>
      <collision>
        <origin xyz="0 0 0.0125"/>
        <geometry>
          <cylinder radius="0.05" length="0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tow_hitch_mass}"/>
        <inertia
          ixx="${((1/12)*tow_hitch_mass)*((3*0.05*0.05)+(0.025*0.025))}" ixy="0" ixz="0"
          iyy="${((1/12)*tow_hitch_mass)*((3*0.05*0.05)+(0.025*0.025))}" iyz="0"
          izz="${(0.5*tow_hitch_mass*0.05*0.05)}"/>
      </inertial>
    </link>

    <link name="cargo_cart_link">
      <visual>
        <origin xyz="-0.2 0 0.0125" rpy="0 0 0" />
        <geometry>
          <box size="0.5 0.643 0.025"/>
          <material name="black"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.2 0 0.0125"/>
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.5*0.5) + (0.643*0.643)))}"/>
        </inertial>
    </link>

    <link name="cargo_cart_mid_link">
      <visual>
        <origin xyz="0 0 -0.1275" rpy="0 0 0" />
        <geometry>
          <box size="0.025 0.643 0.28"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.0725"/>
        <geometry>
          <box size="0.025 0.643 0.28"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.17*0.17)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.17*0.17) + (0.643*0.643)))}"/>
      </inertial>
    </link>

    <link name="cargo_cart_bed_link">
      <visual>
        <origin xyz="-0.2625 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.2625 0 0"/>
        <geometry>
          <box size="0.5 0.643 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cargo_cart_link_mass}"/>
        <inertia
          ixx="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cargo_cart_link_mass)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cargo_cart_link_mass)*((0.5*0.5) + (0.643*0.643)))}"/>
      </inertial>
    </link>


    <gazebo reference="base_link">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <gazebo reference="link1">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <gazebo reference="top_link">  
      <visual>  
        <material>
          <ambient>0.1764 0.4588 0.8509 1.0</ambient>  
          <diffuse>0.1764 0.4588 0.8509 1.0</diffuse>  
          <specular>0.1764 0.4588 0.8509 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual>  
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>


    <joint name="base_to_link1" type="fixed">
      <parent link="base_link"/>
      <child link="link1"/>
      <origin xyz="0.084 0 0.118" rpy="0 0 0"/>
    </joint>


    <!--<joint name="top_link_joint" type="fixed">
      <parent link="base_link"/>
      <child link="top_link" />
      <origin xyz="0.084 0 0.21" rpy="0 0 0"/>
    </joint>-->

    <joint name="tow_hitch_joint" type="fixed">
      <origin xyz="0.084 0 0.21" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="tow_hitch_link" />
    </joint>

    <joint name="cargo_cart_joint" type="fixed">
      <origin xyz="0 0 0.025" rpy="0 0 0" />
      <parent link="tow_hitch_link"/>
      <child link="cargo_cart_link" />
    </joint>

    <joint name="cargo_cart_mid_joint" type="fixed">
      <origin xyz="-0.4625 0 0.0125" rpy="0 0 0" />
      <parent link="cargo_cart_link"/>
      <child link="cargo_cart_mid_link" />
    </joint>

    <joint name="cargo_cart_bed_joint" type="fixed">
      <origin xyz="0 0 -0.255" rpy="0 0 0" />
      <parent link="cargo_cart_mid_link"/>
      <child link="cargo_cart_bed_link" />
    </joint>


    <joint name="left_wheel_holder_joint" type="fixed">
      <parent link="cargo_cart_bed_link"/>
      <child link="left_wheel_holder_link" />
      <origin xyz="-0.4 0.28 -0.0125" rpy="0 0 0" />
    </joint>

    <joint name="$left_wheel_holder_mid_joint" type="fixed">
      <parent link="left_wheel_holder_link"/>
      <child link="left_wheel_holder_mid_link" />
      <origin xyz="0 0.0395 0" rpy="0 0 0" />
    </joint>

    <joint name="right_wheel_holder_joint" type="fixed">
      <parent link="cargo_cart_bed_link"/>
      <child link="right_wheel_holder_link" />
      <origin xyz="-0.4 -0.28 -0.0125" rpy="0 0 0" />
    </joint>

    <joint name="$right_wheel_holder_mid_joint" type="fixed">
      <parent link="right_wheel_holder_link"/>
      <child link="right_wheel_holder_mid_link" />
      <origin xyz="0 -0.0395 0" rpy="0 0 0" />
    </joint>

    <joint name="left_cart_wheel_joint" type="continuous">
      <parent link="left_wheel_holder_mid_link"/>
      <child link="left_cart_wheel_link" />
      <axis xyz="0 1 0" />
      <origin xyz="0 -${(wheel_with/2)} -0.06" rpy="0 0 0"/>
    </joint>

    <joint name="right_cart_wheel_joint" type="continuous">
      <parent link="right_wheel_holder_mid_link"/>
      <child link="right_cart_wheel_link" />
      <axis xyz="0 1 0" />
      <origin xyz="0 ${(wheel_with/2)} -0.06" rpy="0 0 0"/>
    </joint>


    <link name="left_wheel_holder_link">
      <visual>
        <origin xyz="0 0 -0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.0790 0.01"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.0790 0.01"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_holder_mass}"/>
        <inertia
          ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.0790*0.0790)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
          izz="${(((1/12)*wheel_holder_mass)*((0.05*0.05) + (0.0790*0.0790)))}"/>
      </inertial>
    </link> 

    <link name="right_wheel_holder_link">
      <visual>
        <origin xyz="0 0 -0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.0790 0.01"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.0790 0.01"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_holder_mass}"/>
        <inertia
          ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.0790*0.0790)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
          izz="${(((1/12)*wheel_holder_mass)*((0.05*0.05) + (0.0790*0.0790)))}"/>
      </inertial>
    </link> 

      <link name="left_wheel_holder_mid_link">
        <visual>
          <origin xyz="0 0.005 -0.005" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.06"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0.005 -0.055" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.06"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_holder_mass}"/>
          <inertia
            ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.11*0.11)))}" ixy="0" ixz="0"
            iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
            izz="${(((1/12)*wheel_holder_mass)*((0.11*0.11) + (0.05*0.05)))}"/>
        </inertial>
      </link>

      <link name="right_wheel_holder_mid_link">
        <visual>
          <origin xyz="0 -0.005 -0.005" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.06"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 -0.005 -0.055" rpy="0 0 0" />
          <geometry>
            <box size="0.05 0.01 0.06"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_holder_mass}"/>
          <inertia
            ixx="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.11*0.11)))}" ixy="0" ixz="0"
            iyy="${(((1/12)*wheel_holder_mass)*((0.01*0.01) + (0.05*0.05)))}" iyz="0"
            izz="${(((1/12)*wheel_holder_mass)*((0.11*0.11) + (0.05*0.05)))}"/>
        </inertial>
      </link>

      <link name="left_cart_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radu}" length="${wheel_with}"/>
          </geometry>
          <material name="black" />
        </visual>
        <collision>
          <origin xyz="0 0 0.000005" rpy="1.57 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radu}" length="${wheel_with}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" ixy="0" ixz="0"
            iyy="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" iyz="0"
            izz="${(0.5*wheel_mass*0.0759*0.0759)}"/>
        </inertial>
      </link>

      <link name="right_cart_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="1.57 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radu}" length="${wheel_with}"/>
          </geometry>
          <material name="black" />
        </visual>
        <collision>
          <origin xyz="0 0 0.000005" rpy="1.57 0 0"/>
          <geometry>
            <cylinder radius="${wheel_radu}" length="${wheel_with}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" ixy="0" ixz="0"
            iyy="${((1/12)*wheel_mass)*((3*0.0759*0.0759)+(0.0790*0.0790))}" iyz="0"
            izz="${(0.5*wheel_mass*0.0759*0.0759)}"/>
        </inertial>
      </link>

    <!--<transmission name="cargo_cart_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="cargo_cart_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="cargo_cart_joint_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
      <limit lower="-${PI*0.5}" upper="${PI*0.5}" velocity="0" effort="0"/>
      <dynamics damping="${damping_coef}" friction="${friction_coef}" />
            <axis xyz="0 0 1" />-->
  </xacro:macro>
</robot>
