<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass t_length t_width t_height t_mass wheel_radius wheel_pos_z">
    <xacro:property name="cart_link" value="0.5" />
    <xacro:property name="damping_coef" value="0.7" />
    <xacro:property name="friction_coef" value="0.5" />
    <xacro:property name="caster" value="0.05" />
    <xacro:property name="caster_x" value="${(t_length / 2) - 0.05}" />
    <xacro:property name="caster_y" value="${(t_width / 2) - 0.05}" />
    <link name="base_footprint"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
          <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${(width-0.06)} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>


    <link name="hinge">
      <visual>
        <origin xyz="0 0 -0.005" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="0.01"/>
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.025" length="0.01"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="${(2/5) * mass * (0.025 * 0.025)}" ixy="0" ixz="0"
                 iyy="${(2/5) * mass * (0.025 * 0.025)}" iyz="0"
                 izz="${(2/5) * mass * (0.025 * 0.025)}" />
      </inertial>
    </link>

    <link name="laser_footbase">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.035" length="0.094"/>
        </geometry>
        <material name="purple">
            <color rgba="0.4 0.0 0.6 0.5"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.035" length="0.094"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia ixx="${(2/5) * mass * (0.035 * 0.035)}" ixy="0" ixz="0"
                 iyy="${(2/5) * mass * (0.035 * 0.035)}" iyz="0"
                 izz="${(2/5) * mass * (0.035 * 0.035)}" />
      </inertial>
    </link>

    <link name="trailer_cart_link">
      <visual>
        <origin xyz="-0.1475 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.345 0.05 0.04"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="-0.135 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.345 0.05 0.04"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cart_link}"/>
        <inertia
          ixx="${(((1/12)*cart_link)*((0.025*0.025) + (0.37*0.37)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cart_link)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cart_link)*((0.5*0.5) + (0.37*0.37)))}"/>
        </inertial>
    </link>

    <link name="gripper">
      <visual>
        <origin xyz="0 0 -0.05" rpy="0 0 0" />
        <geometry>
          <box size="0.1 0.1 0.2"/>
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="-0.135 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.1 0.1 0.2"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${cart_link}"/>
        <inertia
          ixx="${(((1/12)*cart_link)*((0.025*0.025) + (0.643*0.643)))}" ixy="0" ixz="0"
          iyy="${(((1/12)*cart_link)*((0.025*0.025) + (0.5*0.5)))}" iyz="0"
          izz="${(((1/12)*cart_link)*((0.5*0.5) + (0.643*0.643)))}"/>
        </inertial>
    </link>

    <link name="trailer_base">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${t_length} ${t_width} ${t_height}"/>
          <!-- <mesh filename="" scale="0.001 0.001 0.001"/> -->
        </geometry>
        <material name="blue">
            <color rgba="0.1764 0.4588 0.8509 1.0"/>
        </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${t_length} ${t_width} ${t_height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${t_mass}"/>
        <inertia ixx="${(1/12) * t_mass * ((t_width  * t_width)  + (t_height * t_height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * t_mass * ((t_length * t_length) + (t_height * t_height))}" iyz="0.0"
                 izz="${(1/12) * t_mass * ((t_length * t_length) + (t_width  * t_width))}"/>
      </inertial>
    </link>

    <!-- wheel 4 FR, FL, RL, RR-->
    <!-- 1-->
    <link name="frontL_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="${(2/5) * 0.1 * (caster * caster)}" ixy="0" ixz="0"
                 iyy="${(2/5) * 0.1 * (caster * caster)}" iyz="0"
                 izz="${(2/5) * 0.1 * (caster * caster)}" />
      </inertial>
    </link>

    <gazebo reference="frontL_caster">
        <mu1>0.06</mu1>
        <mu2>0.06</mu2>
    </gazebo>

    <!-- 2-->
    <link name="frontR_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="${(2/5) * 0.1 * (caster * caster)}" ixy="0" ixz="0"
                 iyy="${(2/5) * 0.1 * (caster * caster)}" iyz="0"
                 izz="${(2/5) * 0.1 * (caster * caster)}" />
      </inertial>
    </link>

    <gazebo reference="frontR_caster">
        <mu1>0.06</mu1>
        <mu2>0.06</mu2>
    </gazebo>

    <!-- 3-->
    <link name="rearL_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="${(2/5) * 0.1 * (caster * caster)}" ixy="0" ixz="0"
                 iyy="${(2/5) * 0.1 * (caster * caster)}" iyz="0"
                 izz="${(2/5) * 0.1 * (caster * caster)}" />
      </inertial>
    </link>

    <gazebo reference="rearL_caster">
        <mu1>0.06</mu1>
        <mu2>0.06</mu2>
    </gazebo>

    <!-- 4-->
    <link name="rearR_caster">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
        <material name="black">
            <color rgba="0.0 0.0 0.0 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="${(2/5) * 0.1 * (caster * caster)}" ixy="0" ixz="0"
                 iyy="${(2/5) * 0.1 * (caster * caster)}" iyz="0"
                 izz="${(2/5) * 0.1 * (caster * caster)}" />
      </inertial>
    </link>

    <gazebo reference="rearR_caster">
        <mu1>0.06</mu1>
        <mu2>0.06</mu2>
    </gazebo>
    <!-- wheel FINISH-->


    <gazebo reference="base_link">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>

    <joint name="hinge_z" type="fixed">
      <parent link="base_link"/>
      <child link="hinge"/>
      <origin xyz="0 0 0.096" rpy="0 0 0"/>
    </joint>

    <joint name="laser_footbase_joint" type="fixed">
      <parent link="base_link"/>
      <child link="laser_footbase"/>
      <origin xyz="0.07 0 0.133" rpy="0 0 0"/>
    </joint>

   <joint name="trailer_rev_hinge" type="revolute">
      <parent link="hinge"/>
      <child link="trailer_cart_link"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6981" upper="0.6981" effort="0" velocity="0"/>
      <dynamics damping="${damping_coef}" friction="${friction_coef}" />
    </joint>

    <transmission name="trailer_rev">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="trailer_hinge">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="encoder_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <joint name="trailer_gripper" type="fixed">
      <parent link="trailer_cart_link"/>
      <child link="gripper"/>
      <origin xyz="-0.37 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="trailer_base_joint" type="fixed">
      <parent link="gripper"/>
      <child link="trailer_base"/>
      <origin xyz="-0.5 0 ${(t_height/2)-(0.116 - wheel_pos_z)}" rpy="0 0 0"/>
    </joint>

    <!--wheel joint 4-->
    <joint name="frontL_caster_joint" type="fixed">
      <parent link="trailer_base"/>
      <child link="frontL_caster"/>
      <origin xyz="${caster_x} ${caster_y} ${-((t_height/2) + caster)}" rpy="0 0 0"/>
    </joint>

    <joint name="frontR_caster_joint" type="fixed">
      <parent link="trailer_base"/>
      <child link="frontR_caster"/>
      <origin xyz="${caster_x} ${-caster_y} ${-((t_height/2) + caster)}" rpy="0 0 0"/>
    </joint>

    <joint name="rearR_caster_joint" type="fixed">
      <parent link="trailer_base"/>
      <child link="rearR_caster"/>
      <origin xyz="${-caster_x} ${-caster_y} ${-((t_height/2) + caster)}" rpy="0 0 0"/>
    </joint>

    <joint name="rearL_caster_joint" type="fixed">
      <parent link="trailer_base"/>
      <child link="rearL_caster"/>
      <origin xyz="${-caster_x} ${caster_y} ${-((t_height/2) + caster)}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>
